# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['File', 'FILETYPE']

# Cell
import os
print('os')

# Cell
#file.py
"""
file class define
"""

import os,io

FILETYPE=('DIR','TXT','MD','NOTKNOW')

class File(object):
	"""file base class"""
	def __init__(self, abs_path,filename):
		'''
		'''
		self.path = abs_path
		self.filename = filename
		self.type = 'NOTKNOW'
		self.path_filename = os.path.join(self.path,self.filename)
		try:
			self.stat = os.stat(self.path_filename)
		except Exception as e:
			raise Exception("error {0}: {1}".format(filename, e))

		#is directory?
		if os.path.isdir(self.path_filename):
			self.type='DIR'
		
		_,ext = os.path.splitext(self.filename)
		if ext == '.txt' or ext == '.TXT':
			self.type = 'TXT'
		elif ext == '.md' or ext == '.MD':
			if self.ismdfile(self.path_filename):
				self.type = 'MD'

	@property
	def meta(self):
		return {
			'type':self.type,
			'path':self.path,
			'name':self.filename,
			'size':self.stat.st_size,
    	}

	def ismdfile(self,src_file_path):
		meta_notation = "---"
		with io.open(src_file_path, "rt", encoding="utf-8") as fd:
			textlist = fd.read().lstrip().splitlines()
			if textlist[0] != meta_notation:
				return False
			textlist = textlist[1:]
		try:
			textlist.index(meta_notation)
		except:
			return False

		return True
        	
if __name__ == '__main__':
	f = File("d:\\","data")
	print(f.meta)	
	f = File("c:\\","hiberfil.sys")
	print(f.meta)
	f = File("d:\\data\\simiki\\simiki\\conf_templates\\","gettingstarted.md")
	print(f.meta)
